geographic/continents/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import Continents, ContinentDetailView, register_continent

app_name = 'continents'

urlpatterns = [
    path('class_home/', TemplateView.as_view(template_name='continents/home.html'),name='class_home'),
    path('',Continents.as_view(), name='home'),
    path('<int:pk>/', ContinentDetailView.as_view(),name='continent_detail'),
    path('register_continent/', register_continent,name='register_continent'),
]

geographic/geographic/urls.py
from django.contrib import admin
from django.urls import path, include
from continents.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('continents/',include('continents.urls',namespace='continents')),
    path('countries/',include('countries.urls',namespace='countries')),
    path('people/',include('people.urls',namespace='people')),
    path('capitals/',include('capitals.urls',namespace='capitals')),
]

geographic/people/urls.py
from django.urls import path
from .views import People, register_person

app_name = 'people'

urlpatterns=[
    path('',People.as_view(),name='home'),
    path('register_person',register_person,name='register_person'),
]

geographic/continents/models.py
from django.db import models
from colorful.fields import RGBColorField
# Create your models here.

class Continent(models.Model):
    name = models.CharField(max_length=20,unique=True)
    population = models.PositiveIntegerField()
    color = RGBColorField()

    def __str__(self):
        return self.name

geographic/continents/forms.py
from django import forms
from colorful.fields import RGBColorField
from .models import Continent

class RegisterContinentModelForm(forms.ModelForm):

    class Meta:
        model = Continent
        fields = ['name','population','color']

#    name = forms.CharField(label='nombre')
#    population = forms.IntegerField(label='poblacion',required=False)
#    color = RGBColorField()

geographic/continents/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse #Se importa el objeto HttpResponse para poder retornar la vista.
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from .models import Continent
from django.views.generic.detail import DetailView
from .forms import RegisterContinentModelForm

# Create your views here.

def home(request):
    return render(request, 'continents/home.html')

class Continents(ListView):
    model = Continent
    template_name='continents/continents.html'

class ContinentDetailView(DetailView):
    template_name = 'continents/continent_detail.html'
    model = Continent
#    def get_context_data(self, *args, **kwargs):
#        continent = get_object_or_404(Continent, id=kwargs['id'])
#
#        return {'continent':continent}

def register_continent(request):
    form = RegisterContinentModelForm(request.POST or None)

    if form.is_valid():
        continent = form.save()
        return JsonResponse(
            {
                'name':continent.name,
                'color':continent.color,
                'population':continent.population
            }
        )
    return render(request, 'continents/register_continent.html',{'form':form})

geographic/continents/templates/continents/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Geographic{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  </head>
  <body>
    <div class="container">
      <div class="row">
        <a href="/"><h1>Geographic</h1></a>
          {% block content %}
          {% endblock %}
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.1.0.js" integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function() {
      $('select').material_select();
      $('.datepicker').pickadate({
        selectMonths: true,
        selectYear: 15,
        format: 'yyyy-mm-dd',
        closeOnSelect: true
      });
    });
    </script>
  </body>
</html>

geographic/continents/templates/continents/continent_detail.html
{% extends "continents/base.html" %}
  {% block title %}{{continent.name}}{% endblock %}
{% block content %}
  <h1 style="color:{{continent.color}};">{{ continent.name }}</h1>
  <p><strong>id:</strong>{{ continent.id }}</p>
  <h4>Descripción:</h4>
  <p>{{ continent.description }}</p>
  {% lorem 1 p%}
  <h3>Paises asociados a este continente:</h3>
  {% for country in countries %}
    {% if country.continent.name == continent.name %}
      <p>{{country.name}}</p>
    {% endif %}
  {% endfor %}
<a href="{% url "continents:home" %}">atrás</a>
{% endblock %}

geographic/continents/templates/continents/continents.html
{% extends "continents/base.html" %}
{% block title %}Continents{% endblock %}
{% block content %}
<h1>Continentes del mundo</h1>
{% for continent in object_list %}
<a href="{% url "continents:continent_detail" pk=continent.id %}" style="color:{{continent.color}};text-decoration:none;">
  <div style="border-width: 2px; border-color: #000000; border-style: dotted;">
    <h1>{{ continent.name }}</h1>
    <p>Continent id: {{continent.id}}</p>
  </div>
  <br>
</a>
{% endfor %}
<a href="{% url "continents:register_continent" %}"> <h3>registrar un nuevo contiente</h3> </a>
{% endblock %}

geographic/continents/templates/continents/home.html
{% extends "continents/base.html" %}
{% block content %}
<p>Bienvenido a mi genial aplicación creada gracias a la ayuda de platzi y el profesor David Toca</p>
<p><a href="{% url "continents:home" %}">Clic aquí para ver los continentes</a></p>
<p><a href="{% url "countries:home" %}">Clic aquí para ver los paises</a></p>
<p><a href="{% url "people:home" %}">Personas registradas</a></p>
<p> <a href="{% url "capitals:home" %}">Capitales</a></p>
<p><a href="/admin/">admin</a>
{% endblock %}

geographic/continents/templates/continents/register_continent.html
{% extends 'continents/base.html' %}
{% block title %}registrar continente{% endblock %}
{% block content %}
  <form class="" action="." method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" value="Register">
  </form>
{% endblock %}