geographic/countries/urls.py
from django.urls import path
from .views import Countries, CountryDetailView, SearchCountry, register_country

app_name = 'countries'

urlpatterns =[
    path('',Countries.as_view(),name='home'),
    path('search/<query>/',SearchCountry.as_view(), name='search'),
    path('register/',register_country,name='register_country'),
    path('<code>/',CountryDetailView.as_view(),name='country_detail'),
]

geographic/geographic/urls.py
from django.contrib import admin
from django.urls import path, include
from continents.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('continents/',include('continents.urls',namespace='continents')),
    path('countries/',include('countries.urls',namespace='countries')),
    path('people/',include('people.urls',namespace='people')),
    path('capitals/',include('capitals.urls',namespace='capitals')),
]

geographic/people/urls.py
from django.urls import path
from .views import People, register_person

app_name = 'people'

urlpatterns=[
    path('',People.as_view(),name='home'),
    path('register_person',register_person,name='register_person'),
]

geographic/countries/models.py
from django.db import models

# Create your models here.

class Country(models.Model):
    CLASSIFICATION=(
        ('A','Safe'),
        ('B','Less safe'),
        ('C','Unsafe'),
        ('D','More Unsafe'),
    )
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=3)
    description = models.TextField(max_length=255,blank=True,null=True)
    classification = models.CharField(max_length=1,choices=CLASSIFICATION,default='C')
    continent = models.ForeignKey('continents.Continent',on_delete=models.CASCADE)
    def __str__(self):
        return self.name

    class Meta:
        ordering = ('id',)

geographic/countries/forms.py
from django import forms
from continents.models import Continent
from .models import Country

class RegisterCountryForm(forms.Form):
    continents = Continent.objects.all()
    name = forms.CharField(label='Country name')
    code = forms.CharField(max_length=3,label='Code')
    description = forms.CharField(max_length=255,label='Description')
    classification = forms.ChoiceField(choices=Country().CLASSIFICATION,label='classification')
    continent = forms.ModelChoiceField(queryset=continents,label='continent')

#class RegisterModelCountryForm(forms.ModelForm):
#    class Meta:
#        model = Country
#        fields = ['name','code','description','classification','continent']

geographic/countries/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from .models import Country
from .forms import RegisterCountryForm

# Create your views here.

class Countries(TemplateView):
    template_name='countries/countries.html'

class CountryDetailView(TemplateView):
    template_name='countries/country_detail.html'

    def get_context_data(self, *args, **kwargs):
        code = kwargs['code']
        return {'code':code}

class SearchCountry(ListView):
    template_name = 'countries/search.html'
    model = Country

    def get_queryset(self):
        query = self.kwargs['query']
        return Country.objects.filter(name__contains=query)

def register_country(request):
    form = RegisterCountryForm(request.POST or None)

    if form.is_valid():
        data = form.cleaned_data
        country = Country.objects.create(
            name = data['name'],
            code = data['code'],
            description = data['description'],
            classification = data['classification'],
            continent = data['continent']
        )
        return JsonResponse(
            {
                'name':country.name,
                'code':country.code,
                'classification':country.classification
            }
        )
    return render(request, 'countries/register_country.html',{'form':form})

geographic/countries/templates/countries/countries.html
{% extends "continents/base.html" %}
{% block title %}Countries{% endblock %}
{% block content %}
<h1>Paises del mundo</h1>
{% for country in countries %}
<a href="{% url "countries:country_detail" country.code %}">
  <div style="border-width: 2px; border-color: #000000; border-style: dotted;">
    <h2>{{ country.name | title}}</h2>
    <p><strong>Code: </strong>{{country.code}}</p>
  </div>
</a>
<br>
{% endfor %}
<h3><a href="{% url "countries:register_country" %}">Registrar un nuevo país</a> </h3>
{% endblock %}

geographic/countries/templates/countries/country_detail.html
{% extends "continents/base.html" %}
{% block title %}{{code}}{% endblock %}
{% block content %}

{% for country in countries %}
  {% if country.code == code %}
    <h1>{{ country.name }}</h1>
    <p><strong>Code:</strong>{{ country.code }}</p>
    <h4>Descripción:</h4>
    <p>{{ country.description }}</p>
    {% lorem 5 p %}
  {% endif %}
{% endfor %}
<a href="{% url "countries:home" %}">atrás</a>
{% endblock %}

geographic/countries/templates/countries/register_country.html
{% extends 'continents/base.html' %}
{% block content %}
<form class="" action="." method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" name="" value="Register">
</form>
{% endblock %}

geographic/countries/templates/countries/search.html
{% extends 'continents/base.html' %}
{% block title %}Search Country{% endblock %}
{% block content %}
<h1>Resultados de la busqueda</h1>
  {% for country in object_list %}
    <a href="{% url "countries:country_detail" country.code %}">
      <div style="border-width: 2px; border-color: #000000; border-style: dotted;">
        <h3>{{country.name}}</h3>
        <p>{{country.code}}</p>
      </div>
    </a>
    <br>
  {% endfor %}
{% endblock %}