geographic/geographic/urls.py
from django.contrib import admin
from django.urls import path, include
from continents.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('continents/',include('continents.urls',namespace='continents')),
    path('countries/',include('countries.urls',namespace='countries')),
    path('people/',include('people.urls',namespace='people')),
    path('capitals/',include('capitals.urls',namespace='capitals')),
]

geographic/people/urls.py
from django.urls import path
from .views import People, register_person

app_name = 'people'

urlpatterns=[
    path('',People.as_view(),name='home'),
    path('register_person',register_person,name='register_person'),
]

geographic/people/models.py
from django.db import models

# Create your models here.

class ActiveManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)

class Person(models.Model):
    name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=50)
    born_date = models.DateField(auto_now=False)
    creation_day = models.DateTimeField(auto_now=True)
    phone_number = models.CharField(max_length=30)
    nationalities = models.ManyToManyField('countries.Country')
    is_active = models.BooleanField(default=True)
#    active_manager = ActiveManager()
#    objects = models.Manager() # estas dos lineas me permiten marcar un objeto como cativo o inactivo pero la vaina es que practicamente elimina los objetos porque no os muestra por ningun lado, ni siquiera en el admin, la unica manera de regresarlos seria con el shell

    def __str__(self):
        return self.name

geographic/people/forms.py
from django import forms
from .models import Person
from countries.models import Country

class RegisterPersonFormModel(forms.ModelForm):

    class Meta:
        model = Person
        fields = [
            'name',
            'last_name',
            'born_date',
            'phone_number',
            'nationalities',
            'is_active',
        ]
    def __init__(self, *args, **kwargs):
        super(RegisterPersonFormModel,self).__init__(*args, **kwargs)
        self.fields['born_date'].widget.attrs.update({'class':'datepicker'})

geographic/people/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .forms import RegisterPersonFormModel
from django.http import JsonResponse
from .models import Person
# Create your views here.

class People(TemplateView):
    template_name = 'people/people.html'

def register_person(request):
    form = RegisterPersonFormModel(request.POST or None)

    if form.is_valid():
        person = form.save()
        return JsonResponse(
            {
                'name':person.name
            }
        )
    return render(request,'people/register_person.html',{'form':form})

geographic/people/templates/people/people.html
{% extends 'continents/base.html' %}
{% block title %}People{% endblock %}
{% block content %}
<h1>People</h1>

{% for person in people %}
  <div style="border-style:dotted;border-width:1px;border-width:2px;">
    {% if person.is_active %}
      <h3>nombre</h3>
      <p>{{person.name}}</p>
      <h3>apellido</h3>
      <p>{{person.last_name}}</p>
      <h3>Teléfono</h3>
      <p>{{person.phone_number}}</p>
      <h3>Nacionalidad/es</h3>
      {% for nationality in person.nationalities.all %}
        <p>{{nationality}}</p>
      {% endfor %}
    {% endif %}
  </div>
  <br>
{% endfor %}
<a href="{% url "people:register_person" %}"> <h3>nueva persona</h3> </a>
{% endblock %}

geographic/people/templates/people/register_person.html
{% extends 'continents/base.html' %}
{% block title %}registrar una persona{% endblock %}
{% block content %}
  <form method="post" role="form">
    {% for field in form %}
      {% if field.name == "is_active" %}
        <p>
          {{field.errors}}
          {{field}}
          {{field.label_tag}}
        </p>
      {% else %}
        {{field.errors}}
        {{field.label_tag}}
        {{field}}
      {% endif %}
    {% endfor %}
    {% csrf_token %}
    <br>
  <input type="submit" value="Submit" class="btn btn-primary" />
</form>
{% endblock %}